[tools]
"go:github.com/bufbuild/buf-language-server/cmd/bufls" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/golang/mock/mockgen" = "latest"
"go:github.com/nametake/golangci-lint-langserver" = "latest"
"go:github.com/segmentio/golines" = "latest"
"go:golang.org/x/tools/cmd/godoc" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
"go:google.golang.org/grpc/cmd/protoc-gen-go-grpc" = "latest"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@prettier/plugin-php" = "latest"
"npm:@prettier/plugin-ruby" = "latest"
"npm:@prettier/plugin-xml" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eslint" = "latest"
"npm:eslint-config-prettier" = "latest"
"npm:eslint-plugin-prettier" = "latest"
"npm:eslint_d" = "latest"
"npm:htmllint-cli" = "latest"
"npm:httpsnippet" = "latest"
"npm:jsonlint" = "latest"
"npm:localtunnel" = "latest"
"npm:markdown-it" = "latest"
"npm:prettier" = "latest"
"npm:prettier-plugin-toml" = "latest"
"npm:prettier-pnp" = "latest"
"npm:stylelint" = "latest"
"npm:typescript" = "latest"
"npm:typescript-formatter" = "latest"
"npm:typescript-language-server" = "latest"
"npm:uuid-cli" = "latest"
"npm:vscode-css-languageserver-bin" = "latest"
"npm:vscode-json-languageserver" = "latest"
"npm:yaml-language-server" = "latest"
1password-cli = "latest"
actionlint = "latest"
buf = "latest"
ctop = "latest"
direnv = "latest"
dust = "latest"
go = "latest"
golangci-lint = "latest"
goreleaser = "latest"
helm = "latest"
k9s = "latest"
kubectl = "latest"
kubectx = "latest"
lua = "latest"
neovim = "latest"
node = "lts"
python = "latest"
rclone = "latest"
ripgrep = "latest"
ruby = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
terraform = "latest"
zoxide = "latest"
