[settings]
cargo_binstall = true
experimental = true
legacy_version_file = true
not_found_auto_install = false
idiomatic_version_file_enable_tools = [
    "ruby",
    "python",
    "node",
    "go",
    "terraform",
    "yarn",
]

[settings.status]
show_env = true
show_tools = false

[settings.npm]
bun = true

[settings.pipx]
# Allow mise to install pipx packages without manual installation of pipx.
uvx = true

[settings.ruby]
# Precompiled binaries causes issues with Ruby LSP.
compile = true

[tools]
"aqua:AlexanderGrooff/mermaid-ascii" = "latest"
"aqua:svenstaro/miniserve" = "latest"
"aqua:tldr-pages/tlrc" = "latest"
"cargo:bacon" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-info" = "latest"
"cargo:cargo-show" = "latest"
"cargo:cargo-update" = "latest"
"cargo:dirstat-rs" = "latest"
"cargo:dutree" = "latest"
"cargo:eza" = "latest"
"cargo:kubectl-watch" = "latest"
"cargo:mergiraf" = "latest"
"cargo:paper-terminal" = "latest"
"cargo:parallel-disk-usage" = { version = "latest", bin = "pdu" }
"cargo:pastel" = "latest"
"cargo:riffdiff" = "latest"
"github:stacklok/toolhive" = "latest"
"go:github.com/rakyll/hey" = "latest"
"go:google.golang.org/grpc/cmd/protoc-gen-go-grpc" = "latest"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "latest"
"npm:@github/copilot-language-server" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@prettier/plugin-php" = "latest"
"npm:claude-plugins" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eslint" = "latest"
"npm:eslint-config-prettier" = "latest"
"npm:eslint-plugin-prettier" = "latest"
"npm:eslint_d" = "latest"
"npm:htmllint-cli" = "latest"
"npm:http-server" = "latest"
"npm:httpsnippet" = "latest"
"npm:jsonlint" = "latest"
"npm:localtunnel" = "latest"
"npm:markdown-it" = "latest"
"npm:oxfmt" = "latest"
"npm:oxlint" = "latest"
"npm:prettier" = "latest"
"npm:prettier-plugin-toml" = "latest"
"npm:prettier-pnp" = "latest"
"npm:skills" = "latest"
"npm:stylelint" = "latest"
"npm:svgo" = "latest"
"npm:typescript" = "latest"
"npm:typescript-formatter" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-css-languageserver-bin" = "latest"
"npm:vscode-json-languageserver" = "latest"
"npm:yaml-language-server" = "latest"
"npm:yarn" = "latest"
"pipx:ansible-lint" = "latest"
"pipx:dmgbuild" = "latest"
"pipx:fonttools" = "latest"
"pipx:pipx" = "latest"
"pipx:toml-sort" = "latest"
"pipx:yamllint" = "latest"
1password = "latest"
actionlint = "latest"
argo-rollouts = "latest"
argocd = "latest"
atuin = "latest"
aws-cli = "latest"
bat = "latest"
bat-extras = "latest"
buf = "latest"
bun = "latest"
cargo-binstall = "latest"
cloudflared = "latest"
crane = "latest"
ctop = "latest"
difftastic = "latest"
direnv = "latest"
dua = "latest"
dust = "latest"
evans = "latest"
fd = "latest"
fzf = "latest"
gemini = "latest"
gh = "latest"
gitu = "latest"
go = "latest"
gofumpt = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
golines = "latest"
goreleaser = "latest"
grpcurl = "latest"
hadolint = "latest"
helm = "latest"
helmfile = "latest"
hexyl = "latest"
hivemind = "latest"
hwatch = "latest"
jq = "latest"
jwt = "latest"
jwtui = "latest"
k3d = "latest"
k9s = "latest"
kubecm = "latest"
kubectl = "latest"
kubectx = "latest"
kubelogin = "latest"
kubens = "latest"
kustomize = "latest"
lua = "latest"
lua-language-server = "latest"
markdownlint-cli2 = "latest"
node = "lts"
opencode = "latest"
opentofu = "latest"
pnpm = "latest"
python = "latest"
rclone = "latest"
restish = "latest"
ripgrep = "latest"
ruby = "latest"
rust = { version = "latest", components = "rust-analyzer,rust-src" }
sccache = "latest"
shellcheck = "latest"
shfmt = "latest"
slsa-verifier = "latest"
sops = "latest"
starship = "latest"
staticcheck = "latest"
stern = "latest"
talosctl = "latest"
taplo = "latest"
terraform = "latest"
terraform-ls = "latest"
tflint = "latest"
ubi = "latest"
usage = "latest"
uv = "latest"
watchexec = "latest"
yj = "latest"
yq = "latest"
zig = "latest"
zls = "latest"
zoxide = "latest"

# Install ansible with passlib and bcrypt<4.1, as passlib is not compatible with
# bcrypt 4.1 or later.
[tools."pipx:ansible"]
version = "latest"
uvx_args = "--with-executables-from=ansible-core --with=passlib --with='bcrypt<4.1'"
