[settings]
cargo_binstall = true
experimental = true
legacy_version_file = true
not_found_auto_install = false

[settings.status]
missing_tools = "never"
show_env = true
show_tools = false

[tools]
"cargo:bacon" = "latest"
"cargo:bat" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-info" = "latest"
"cargo:cargo-update" = "latest"
"cargo:dirstat-rs" = "latest"
"cargo:hexyl" = "latest"
"cargo:kubectl-watch" = "latest"
"cargo:paper-terminal" = "latest"
"cargo:tlrc" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/hashicorp/terraform-ls" = "latest"
"go:github.com/rakyll/hey" = "latest"
"go:github.com/rogpeppe/godef" = "latest"
"go:go.uber.org/mock/mockgen" = "latest"
"go:golang.org/x/tools/cmd/godoc" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
"go:google.golang.org/grpc/cmd/protoc-gen-go-grpc" = "latest"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@prettier/plugin-php" = "latest"
"npm:@prettier/plugin-ruby" = "latest"
"npm:@prettier/plugin-xml" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eslint" = "latest"
"npm:eslint-config-prettier" = "latest"
"npm:eslint-plugin-prettier" = "latest"
"npm:eslint_d" = "latest"
"npm:htmllint-cli" = "latest"
"npm:httpsnippet" = "latest"
"npm:jsonlint" = "latest"
"npm:localtunnel" = "latest"
"npm:markdown-it" = "latest"
"npm:prettier" = "latest"
"npm:prettier-plugin-toml" = "latest"
"npm:prettier-pnp" = "latest"
"npm:stylelint" = "latest"
"npm:typescript" = "latest"
"npm:typescript-formatter" = "latest"
"npm:typescript-language-server" = "latest"
"npm:uuid-cli" = "latest"
"npm:vscode-css-languageserver-bin" = "latest"
"npm:vscode-json-languageserver" = "latest"
"npm:yaml-language-server" = "latest"
"ubi:BurntSushi/ripgrep" = { version = "latest", exe = "rg" }     # ripgrep
"ubi:DarthSim/hivemind" = "latest"                                # hivemind
"ubi:ajeetdsouza/zoxide" = "latest"                               # zoxide
"ubi:altsem/gitu" = "latest"                                      # gitu
"ubi:argoproj/argo-cd" = { version = "latest", exe = "argocd" }   # Argo CD
"ubi:blacknon/hwatch" = "latest"                                  # hwatch
"ubi:bootandy/dust" = "latest"                                    # dust
"ubi:bufbuild/buf" = "latest"                                     # buf
"ubi:danielgtaylor/restish" = "latest"                            # restish
"ubi:derailed/k9s" = "latest"                                     # k9s
"ubi:getsops/sops" = "latest"                                     # sops
"ubi:golangci/golangci-lint" = "latest"                           # golangci-lint
"ubi:goreleaser/goreleaser" = "latest"                            # goreleaser
"ubi:jwt-rs/jwt-ui" = { version = "latest", exe = "jwtui" }       # jwtui
"ubi:mike-engel/jwt-cli" = { version = "latest", exe = "jwt" }    # jwt
"ubi:mozilla/sccache" = "latest"                                  # sccache
"ubi:mvdan/gofumpt" = "latest"                                    # gofumpt
"ubi:nametake/golangci-lint-langserver" = "latest"                # golangci-lint-langserver
"ubi:opentofu/opentofu" = { version = "latest", exe = "tofu" }    # tofu
"ubi:rclone/rclone" = "latest"                                    # rclone
"ubi:sclevine/yj" = "latest"                                      # yj
"ubi:segmentio/golines" = "latest"                                # golines
"ubi:siderolabs/talos" = { version = "latest", exe = "talosctl" } # talosctl
"ubi:starship/starship" = "latest"                                # starship
"ubi:tamasfe/taplo" = { version = "latest", matching = "full" }   # taplo
"ubi:terraform-linters/tflint" = "latest"                         # tflint
"ubi:watchexec/watchexec" = "latest"                              # watchexec
"ubi:wilfred/difftastic" = { version = "latest", exe = "difft" }  # difftastic
1password-cli = "latest"
actionlint = "latest"
cargo-binstall = "latest"
ctop = "latest"
direnv = "latest"
eza = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
hadolint = "latest"
helm = "latest"
helmfile = "latest"
jq = "latest"
kubectl = "latest"
kubectx = "latest"
kustomize = "latest"
lua = "latest"
node = "lts"
python = "latest"
ruby = "latest"
rust = "latest"
shellcheck = "latest"
shfmt = "latest"
terraform = "latest"
ubi = "latest"
usage = "latest"
yq = "latest"
