[settings]
cargo_binstall = true
experimental = true
legacy_version_file = true
not_found_auto_install = false

[settings.status]
show_env = true
show_tools = false

[tools]
"aqua:AlexanderGrooff/mermaid-ascii" = "latest"
"aqua:sharkdp/hexyl" = "latest"
"aqua:tldr-pages/tlrc" = "latest"
"cargo:bacon" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-info" = "latest"
"cargo:cargo-show" = "latest"
"cargo:cargo-update" = "latest"
"cargo:dirstat-rs" = "latest"
"cargo:eza" = "latest"
"cargo:kubectl-watch" = "latest"
"cargo:paper-terminal" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/rakyll/hey" = "latest"
"go:github.com/rogpeppe/godef" = "latest"
"go:go.uber.org/mock/mockgen" = "latest"
"go:golang.org/x/tools/cmd/godoc" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
"go:google.golang.org/grpc/cmd/protoc-gen-go-grpc" = "latest"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@prettier/plugin-php" = "latest"
"npm:@prettier/plugin-ruby" = "latest"
"npm:@prettier/plugin-xml" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eslint" = "latest"
"npm:eslint-config-prettier" = "latest"
"npm:eslint-plugin-prettier" = "latest"
"npm:eslint_d" = "latest"
"npm:htmllint-cli" = "latest"
"npm:httpsnippet" = "latest"
"npm:jsonlint" = "latest"
"npm:localtunnel" = "latest"
"npm:markdown-it" = "latest"
"npm:prettier" = "latest"
"npm:prettier-plugin-toml" = "latest"
"npm:prettier-pnp" = "latest"
"npm:stylelint" = "latest"
"npm:typescript" = "latest"
"npm:typescript-formatter" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-css-languageserver-bin" = "latest"
"npm:vscode-json-languageserver" = "latest"
"npm:yaml-language-server" = "latest"
1password-cli = "latest"
actionlint = "latest"
argocd = "latest"
bat = "latest"
buf = "latest"
cargo-binstall = "latest"
ctop = "latest"
difftastic = "latest"
direnv = "latest"
dust = "latest"
fzf = "latest"
gh = "latest"
gitu = "latest"
go = "latest"
gofumpt = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
golines = "latest"
goreleaser = "latest"
hadolint = "latest"
helm = "latest"
helmfile = "latest"
hivemind = "latest"
hwatch = "latest"
jq = "latest"
jwt = "latest"
jwtui = "latest"
k9s = "latest"
kubectl = "latest"
kubectx = "latest"
kustomize = "latest"
lua = "latest"
node = "lts"
opentofu = "latest"
python = "latest"
rclone = "latest"
restish = "latest"
ripgrep = "latest"
ruby = "latest"
rust = "latest"
sccache = "latest"
shellcheck = "latest"
shfmt = "latest"
sops = "latest"
starship = "latest"
staticcheck = "latest"
talosctl = "latest"
taplo = "latest"
terraform = "latest"
terraform-ls = "latest"
tflint = "latest"
ubi = "latest"
usage = "latest"
watchexec = "latest"
yj = "latest"
yq = "latest"
zoxide = "latest"
