[tools]
actionlint = "latest"
bat = "latest"
buf = "latest"
ctop = "latest"
direnv = "latest"
dust = "latest"
exa = "latest"
go = "latest"
golangci-lint = "latest"
goreleaser = "latest"
helm = "latest"
k9s = "latest"
kubectl = "latest"
kubectx = "latest"
lua = "latest"
neovim = "latest"
node = "lts"
python = "latest"
rclone = "latest"
ripgrep = "latest"
ruby = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
terraform = "latest"
zoxide = "latest"
