[settings]
cargo_binstall = true
experimental = true
legacy_version_file = true
not_found_auto_install = false

[settings.status]
missing_tools = "never"
show_env = true
show_tools = false

[tools]
"cargo:bacon" = "latest"
"cargo:bat" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-info" = "latest"
"cargo:cargo-update" = "latest"
"cargo:difftastic" = "latest"
"cargo:dirstat-rs" = "latest"
"cargo:eza" = "latest"
"cargo:gitu" = "latest"
"cargo:hexyl" = "latest"
"cargo:hwatch" = "latest"
"cargo:jwt-cli" = "latest"
"cargo:kubectl-watch" = "latest"
"cargo:paper-terminal" = "latest"
"cargo:sccache" = "latest"
"cargo:tlrc" = "latest"
"cargo:ubi" = "latest"
"cargo:watchexec-cli" = "latest"
"go:github.com/DarthSim/hivemind" = "latest"
"go:github.com/bufbuild/buf-language-server/cmd/bufls" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/golang/mock/mockgen" = "latest"
"go:github.com/hashicorp/terraform-ls" = "latest"
"go:github.com/nametake/golangci-lint-langserver" = "latest"
"go:github.com/rakyll/hey" = "latest"
"go:github.com/rhysd/actionlint/cmd/actionlint" = "latest"
"go:github.com/rogpeppe/godef" = "latest"
"go:github.com/segmentio/golines" = "latest"
"go:golang.org/x/tools/cmd/godoc" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/vuln/cmd/govulncheck" = "latest"
"go:google.golang.org/grpc/cmd/protoc-gen-go-grpc" = "latest"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "latest"
"go:mvdan.cc/gofumpt" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@prettier/plugin-php" = "latest"
"npm:@prettier/plugin-ruby" = "latest"
"npm:@prettier/plugin-xml" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eslint" = "latest"
"npm:eslint-config-prettier" = "latest"
"npm:eslint-plugin-prettier" = "latest"
"npm:eslint_d" = "latest"
"npm:htmllint-cli" = "latest"
"npm:httpsnippet" = "latest"
"npm:jsonlint" = "latest"
"npm:localtunnel" = "latest"
"npm:markdown-it" = "latest"
"npm:prettier" = "latest"
"npm:prettier-plugin-toml" = "latest"
"npm:prettier-pnp" = "latest"
"npm:stylelint" = "latest"
"npm:typescript" = "latest"
"npm:typescript-formatter" = "latest"
"npm:typescript-language-server" = "latest"
"npm:uuid-cli" = "latest"
"npm:vscode-css-languageserver-bin" = "latest"
"npm:vscode-json-languageserver" = "latest"
"npm:yaml-language-server" = "latest"
1password-cli = "latest"
argocd = "latest"
buf = "latest"
ctop = "latest"
direnv = "latest"
dust = "latest"
fzf = "latest"
github-cli = "latest"
go = "latest"
golangci-lint = "latest"
goreleaser = "latest"
hadolint = "latest"
helm = "latest"
jq = "latest"
k9s = "latest"
kubectl = "latest"
kubectx = "latest"
kustomize = "latest"
lua = "latest"
node = "lts"
python = "latest"
rclone = "latest"
ripgrep = "latest"
ruby = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
talosctl = "latest"
terraform = "latest"
tflint = "latest"
usage = "latest"
yj = "latest"
yq = "latest"
zoxide = "latest"
