[settings]
cargo_binstall = true
experimental = true
legacy_version_file = true
not_found_auto_install = false
idiomatic_version_file_enable_tools = [
    "ruby",
    "python",
    "node",
    "go",
    "terraform",
    "yarn",
]

[settings.status]
show_env = true
show_tools = false

[settings.npm]
# TODO: Re-enable bun when freezing issue is resolved:
# https://github.com/jdx/mise/discussions/4995
bun = false

[settings.pipx]
# Allow mise to install pipx packages without manual installation of pipx.
uvx = true

[settings.ruby]
ruby_install = true

[tools]
"aqua:AlexanderGrooff/mermaid-ascii" = "latest"
"aqua:tldr-pages/tlrc" = "latest"
"cargo:bacon" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-edit" = "latest"
"cargo:cargo-info" = "latest"
"cargo:cargo-show" = "latest"
"cargo:cargo-update" = "latest"
"cargo:dirstat-rs" = "latest"
"cargo:eza" = "latest"
"cargo:kubectl-watch" = "latest"
"cargo:mergiraf" = "latest"
"cargo:paper-terminal" = "latest"
"cargo:pastel" = "latest"
"github:spinel-coop/rv" = "latest"
"github:stacklok/toolhive" = "latest"
"go:github.com/rakyll/hey" = "latest"
"go:google.golang.org/grpc/cmd/protoc-gen-go-grpc" = "latest"
"go:google.golang.org/protobuf/cmd/protoc-gen-go" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@github/copilot-language-server" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@modelcontextprotocol/server-memory" = "latest"
"npm:@modelcontextprotocol/server-sequential-thinking" = "latest"
"npm:@openai/codex" = "latest"
"npm:@prettier/plugin-php" = "latest"
"npm:@upstash/context7-mcp" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eslint" = "latest"
"npm:eslint-config-prettier" = "latest"
"npm:eslint-plugin-prettier" = "latest"
"npm:eslint_d" = "latest"
"npm:htmllint-cli" = "latest"
"npm:httpsnippet" = "latest"
"npm:jsonlint" = "latest"
"npm:localtunnel" = "latest"
"npm:markdown-it" = "latest"
"npm:prettier" = "latest"
"npm:prettier-plugin-toml" = "latest"
"npm:prettier-pnp" = "latest"
"npm:stylelint" = "latest"
"npm:typescript" = "latest"
"npm:typescript-formatter" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vibe-kanban" = "latest"
"npm:vscode-css-languageserver-bin" = "latest"
"npm:vscode-json-languageserver" = "latest"
"npm:yaml-language-server" = "latest"
"npm:yarn" = "latest"
"pipx:ansible" = { version = "latest", uvx_args = "--with-executables-from ansible-core" }
"pipx:ansible-lint" = "latest"
"pipx:dmgbuild" = "latest"
"pipx:fonttools" = "latest"
"pipx:pipx" = "latest"
"pipx:yamllint" = "latest"
"ubi:rails/rails-new" = "latest"
actionlint = "latest"
argo-rollouts = "latest"
argocd = "latest"
aws-cli = "latest"
bat = "latest"
bat-extras = "latest"
buf = "latest"
cargo-binstall = "latest"
crane = "latest"
ctop = "latest"
difftastic = "latest"
direnv = "latest"
dust = "latest"
evans = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
gitu = "latest"
go = "latest"
gofumpt = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
golines = "latest"
goreleaser = "latest"
grpcurl = "latest"
hadolint = "latest"
helm = "latest"
helmfile = "latest"
hexyl = "latest"
hivemind = "latest"
hugo-extended = "latest"
hwatch = "0.3.18"
jq = "latest"
jwt = "latest"
jwtui = "latest"
k3d = "latest"
k9s = "latest"
kubecm = "latest"
kubectl = "latest"
kubectx = "latest"
kubelogin = "latest"
kubens = "latest"
kustomize = "latest"
lua = "latest"
node = "lts"
opentofu = "latest"
pnpm = "latest"
python = "latest"
rclone = "latest"
restish = "0.20.0"
ripgrep = "latest"
ruby = "latest"
rust = { version = "latest", components = "rust-analyzer,rust-src" }
sccache = "latest"
shellcheck = "latest"
shfmt = "latest"
slsa-verifier = "latest"
sops = "latest"
starship = "latest"
staticcheck = "latest"
stern = "latest"
talosctl = "latest"
taplo = "latest"
terraform = "latest"
terraform-ls = "latest"
tflint = "latest"
ubi = "latest"
usage = "latest"
uv = "latest"
watchexec = "latest"
yj = "latest"
yq = "latest"
zoxide = "latest"
